// <auto-generated />
namespace HospitalPrivadoHP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RolID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RolID));
        
        string IMigrationMetadata.Id
        {
            get { return "201810142225237_RolID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
